### ISSUE TITLE
could you please share your pretrained model？

### ISSUE THREAD

**Issue by anguoyang** [JohnnyHopp/PaDiM-EfficientNet_NS-and-PaDiM-EfficientNetV2#1]

**Comment by JohnnyHopp** [comment]
Hi, @anguoyang , here's the [trained distribution parameters of EfficientNetV2](https://drive.google.com/drive/folders/1jDQ0JPBbfG37N40GVg_K_ZZSTHOhaCYz?usp=sharing), please check it out. If you have any further questions, just let me know.
