### ISSUE TITLE
Standalone predict.py?

### ISSUE THREAD

**Issue by danielsoy** [JohnnyHopp/PaDiM-EfficientNet_NS-and-PaDiM-EfficientNetV2#3]
Hey Johnny, thanks for sharing your project!

I was wondering if you are able to provide at some point in time, a predict.py script.

So we can infer anomalies on single images, in a real life scenario, after the training stage is
 
completed.

On this video, you can see an implementation of Padim https://github.com/OpenAOI/anodet.

https://www.youtube.com/watch?v=W4-ZtpJtE5c&ab_channel=tektronix475

I would like to do the same tests, with your PaDiM-EfficientNetV2

Thank you.

**Comment by JohnnyHopp** [comment]
Hi @danielsoy, sorry for the late relpy. I'm busy recently, so I'm not able to implement the prediction script now. You can try to implement it by referring to the repo you shared. It's not complicated, just be careful about the normalization things in my experience^_^. 

If you have any further questions, I'm willing to discuss with you.
